// user interface
export const NAV_BAR = "NAV_BAR"
export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR"
export const TOGGLE_SUCCESS_SNACKBAR = "TOGGLE_SUCCESS_SNACKBAR"
export const CHANGE_STAGE = "CHANGE_STAGE"
export const TOGGLE_EDIT_RULE_FORM = "TOGGLE_EDIT_RULE_FORM"
export const TOGGLE_CREATE_RULE_FORM = "TOGGLE_CREATE_RULE_FORM"
export const TOGGLE_BILLING_FORM = "TOGGLE_BILLING_FORM"
export const TOGGLE_SHORTCUT_PANEL = "TOGGLE_SHORTCUT_PANEL"
export const TOGGLE_CREATE_CHANNEL_FORM = "TOGGLE_CREATE_CHANNEL_FORM"
export const TOGGLE_CREATE_STAGE_FORM = "TOGGLE_CREATE_STAGE_FORM"

// user authentication
export const AUTH_ERROR = "AUTH_ERROR"
export const LOG_IN_USER = "LOG_IN_USER"
export const LOG_IN_ERROR = "LOG_IN_ERROR"

// channels
export const CREATE_CHANNEL_FAILURE = "CREATE_CHANNEL_FAILURE"
export const FETCH_CHANNELS_SUCCESS = "FETCH_CHANNELS_SUCCESS"
export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL"
export const ADD_STAGE_TO_CURRENT_CHANNEL = "ADD_STAGE_TO_CURRENT_CHANNEL"
export const REMOVE_CHANNEL = "REMOVE_CHANNEL"
export const ADD_CHANNEL_SUCCESS = "ADD_CHANNEL_SUCCESS"
export const FETCH_CHANNELS_REQUEST = "FETCH_CHANNELS_REQUEST"

// stages
export const CREATE_STAGE_SUCCESS = "CREATE_STAGE_SUCCESS"
export const CREATE_STAGE_FAILURE = "CREATE_STAGE_FAILURE"
export const REMOVE_STAGES = "REMOVE_STAGES"
export const SET_CURRENT_STAGE = "SET_CURRENT_STAGE"
export const REMOVE_STAGE_SUCCESS = "REMOVE_STAGE_SUCCESS"
export const REMOVE_STAGE_FAILURE = "REMOVE_STAGE_FAILURE"

// access logs
export const SET_LOGS_REQUEST = "SET_LOGS_REQUEST"
export const SET_LOGS_SUCCESS = "SET_LOGS_SUCCESS"
export const SET_LOGS_FAILURE = "SET_LOGS_FAILURE"
export const SET_LOG = "SET_LOG"
export const DELETE_LOGS = "DELETE_LOGS"
export const LOGS_SEARCH_TEXT = "LOGS_SEARCH_TEXT"

// sub-users
export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS"
export const SET_USERS_REQUEST = "SET_USERS_REQUEST"
export const SET_USERS_FAILURE = "SET_USERS_FAILURE"
export const USER_ERROR_FAILURE = "USER_ERROR_FAILURE"
export const SET_USER = "SET_USER"
export const ADD_USER = "ADD_USER"
export const DELETE_USER = "DELETE_USER"
export const CHANGE_USER_PRIVILEGES = "CHANGE_USER_PRIVILAGES"

// webhooks rules
export const SET_RULES_SUCCESS = "SET_RULES_SUCCESS"
export const SET_RULES_REQUEST = "SET_RULES_REQUEST"
export const SET_RULES_FAILURE = "SET_RULES_FAILURE"
export const ADD_RULE = "ADD_RULE"
export const SET_RULE = "SET_RULE"
export const EDIT_RULE = "EDIT_RULE"
export const DELETE_RULE = "DELETE_RULE"
export const SET_TEST_RESPONSE = "SET_TEST_RESPONSE"

// user settings
export const SET_USER_SETTINGS_SUCCESS = "SET_USER_SETTINGS_SUCCESS"
export const SET_USER_SETTINGS_REQUEST = "SET_USER_SETTINGS_REQUEST"
export const SET_USER_SETTINGS_FAILURE = "SET_USER_SETTINGS_FAILURE"
export const SETTINGS_ERROR = "SETTINGS_ERROR"
