# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install --production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: update /etc/apt/sources.list for apt-get update
          command: |
            sudo echo "deb http://deb.debian.org/debian jessie main" > /etc/apt/sources.list
            sudo echo "deb http://deb.debian.org/debian stable-updates main" >> /etc/apt/sources.list
            sudo apt-get update && apt-get install -y awscli

      # - run: |
#           sudo echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
#           sudo sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
#           sudo apt-get -o Acquire::Check-Valid-Until=false update

      # - run: sudo apt-get update && sudo apt-get install -y python-dev
      # - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      # - run: sudo python get-pip.py
      # - run: sudo pip install awscli --upgrade
      # - run:

      - run: aws --version
      - run: aws s3 ls
      - run: CI=false OAUTH2_GOOGLE_CLIENT_ID=73206489358-hq2cbrum1dq3pt6b6fovpr9nij68t708.apps.googleusercontent.com OAUTH2_GITHUB_CLIENT_ID=ed52156c43808882014a STRIPE_KEY=pk_test_qMst2t2l3YbB2OQJh40wE3eq npm run build
      - run: aws s3 sync build/ s3://apphooks-frontend --delete
      - run: aws cloudfront create-invalidation --distribution-id E1K5SM215FMFYB --paths /*

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
